import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PageTransitionEffect from "./page-transition";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
const geistNoticia = localFont({
  src: "./fonts/NoticiaText-Regular.ttf",
  variable: "--font-noticia-regular",
  weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistNoticia.variable} antialiased`}
      >
       
          <PageTransitionEffect>{children}</PageTransitionEffect>
 
        
      </body>
    </html>
  );
}
